project_id = "nimrggpqcvgpgdmcermb"

[functions.generate-interior]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.get-credits]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.use-credit]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false